### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by SupperCraft5000** [Hurdock/gta5-ragemp-server#1]
When i start the Server i geht the error "Cannot read property 'data' of undefined"

Screen: https://pic.shadowgaming.de/upload/2827163220.png

**Comment by vatto1337** [comment]
Data: [0] loaded. 

Other systems need the databox data to load properly, try to copy my database at least to make it work.

**Comment by thug-thug** [comment]
where i put the database? pls u can explain how to install the server?

**Comment by thug-thug** [comment]
I have this erro too 
pic: https://i.imgur.com/BHLlHZ9.png
i put you backup, update you db backup
